# Generated by Django 3.2.7 on 2022-03-16 06:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8c8c064b-ff4e-4ee9-92c6-4a6e7bc9db81'), primary_key=True, serialize=False),
        ),
    ]
