# Generated by Django 3.2.7 on 2022-03-16 08:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bb41f39-e328-4512-97d3-98f3b819b73b'), primary_key=True, serialize=False),
        ),
    ]
