# Generated by Django 3.2.7 on 2022-03-16 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0019_alter_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.UUID('af468fd5-7523-4eeb-813d-b2331b2958e8'), primary_key=True, serialize=False),
        ),
    ]
